version: '3.8'
services:

  web:
    container_name: tsel-web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - db
    ports:
     - 80:8000

  db:
    container_name: tsel-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: data_form

  redisdb:
    container_name: redisdb
    image: redis:7.0
    ports:
      - 6379:6379

  adminer:
    container_name: tsel-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080